export const EXTERNAL_COMMANDS = {
  HADES: {
    ROLE: {
      LIST: 'HADES.ROLE.LIST',
      GET: 'HADES.ROLE.GET',
    },
    USER: {
      CREATE: 'HADES.USER.CREATE',
      UPDATE: 'HADES.USER.UPDATE',
      LIST: 'HADES.USER.LIST',
      GET: 'HADES.USER.GET',
      ACCOUNT: {
        SEARCH_ACCOUNT_BY_EMAIL: 'HADES.USER.SEARCH.ACCOUNT.BY.EMAIL',
        SEARCH_ACCOUNT_BY_USERNAME: 'HADES.USER.SEARCH.ACCOUNT.BY.USERNAME',
      },
    },
    SESSION: {
      CREATE_ACTIVE: 'HADES.SESSION.CREATE.ACTIVE',
      CREATE_INVALID: 'HADES.SESSION.CREATE.INVALID',
      ARCHIVE: 'HADES.SESSION.ARCHIVE',
      UPDATE: 'HADES.SESSION.UPDATE',
      INCREMENT_FAILED_ATTEMPTS: 'HADES.SESSION.INCREMENT_FAILED_ATTEMPTS',
      ACTIVATE_INVALID: 'HADES.SESSION.ACTIVATE_INVALID',
      TRANSITION_STATUS: 'HADES.SESSION.TRANSITION_STATUS',
      GET: 'HADES.SESSION.GET',
      LIST: 'HADES.SESSION.LIST',
    },
    ASSIGNMENT: {
      LIST: 'HADES.ASSIGNMENT.LIST',
      GET: 'HADES.ASSIGNMENT.GET',
    },
    PERMISSION: {
      LIST: 'HADES.PERMISSION.LIST',
      GET: 'HADES.PERMISSION.GET',
    },
    POLICY: {
      LIST: 'HADES.POLICY.LIST',
      GET: 'HADES.POLICY.GET',
    },
  },
};
