export const INTERNAL_COMMANDS = {
  AUTHENTICATION: {
    WARP_ABOARD: 'AUTHENTICATION.WARP_ABOARD',
    WARP_ENGAGE: 'AUTHENTICATION.WARP_ENGINE',
    WARP_DISENGAGE: 'AUTHENTICATION.WARP_DISENGAGE',
    WARP_EJECT: 'AUTHENTICATION.WARP_EJECT',
  },
};
